play-with-go/play-with-go

- js/post-layout.js
It's not yet available in Chrome. Use a simpler local alternative for
now.
> js: "polyfill" String.prototype.replaceAll

- cmd/controller/controller.go
- cmd/controller/flag.go
- docker-compose.yml
- go.mod
Auth is provided via a secure cookie that the user is granted upon
successful auth in the PWD world.
Fixes #43
> cmd/controller: secure using CORS and auth

- _config-website.yml
- _config.yml
- docker-compose-website.yaml
This compose file should be used with this documentation
https://github.com/play-with-go/play-with-go/wiki/Building-and-deploying-the-website
to generate and publish the webiste
> Add docker-compose file to build website

- cmd/controller/controller.go
> cmd/controller: check for block key in non-dev environment

- cmd/controller/controller.go
- cmd/controller/flag.go
> cmd/controller: support multiple origins

- _posts/2020-10-15-get-started-with-go.markdown
- guides/2020-10-15-get-started-with-go/en_log.txt
- guides/2020-10-15-get-started-with-go/guide.cue
- guides/2020-10-15-get-started-with-go/out/gen_out.cue
- js/post-layout.js
This ensures that we also include any attribute values, e.g. anchor href
links.
> js: replace innerHTML of node when executing the guide templates

- _sass/_layout.scss
> Add pointer cursor to file upload code blocks

- _sass/_layout.scss
- _sass/_post-layout.scss
> Adjust layout to make terminal hight display correctly

- go.mod
- go.sum
- guides/2020-09-01-basic-go-modules-example/go115_en_log.txt
- guides/2020-09-01-basic-go-modules-example/out/gen_out.cue
- guides/2020-10-07-intro-to-play-with-go-dev/go115_en_log.txt
- guides/2020-10-07-intro-to-play-with-go-dev/out/gen_out.cue
- guides/2020-10-15-get-started-with-go/go115_en_log.txt
- guides/2020-10-15-get-started-with-go/out/gen_out.cue
- guides/2020-10-19-go-fundamentals/go115_en_log.txt
- guides/2020-10-19-go-fundamentals/out/gen_out.cue
- guides/2020-11-05-tools-as-dependencies/go115_en_log.txt
- guides/2020-11-05-tools-as-dependencies/out/gen_out.cue
* get better error messages when CUE is invalid
* achieve a higher signal to noise ratio in guides' *_log.txt files
> deps: use latest preguide for CUE error and logging improvements

- .github/workflows/test.yml
- .github/workflows/testmac.yml
- internal/ci/workflows.cue
> ci: only race test on daily scheduled build

- _posts/2020-10-07-intro-to-play-with-go-dev_go115_en.markdown
- _posts/2020-10-15-get-started-with-go_go115_en.markdown
- _posts/2020-10-19-go-fundamentals_go115_en.markdown
- _posts/2020-11-05-tools-as-dependencies_go115_en.markdown
- _posts/2020-11-08-retracting-module-versions_go116_en.markdown
- go.mod
- go.sum
- guides/2020-09-01-basic-go-modules-example/out/gen_out.cue
- guides/2020-10-07-intro-to-play-with-go-dev/out/gen_out.cue
- guides/2020-10-15-get-started-with-go/out/gen_out.cue
- guides/2020-10-19-go-fundamentals/out/gen_out.cue
- guides/2020-11-05-tools-as-dependencies/go115_en_log.txt
- guides/2020-11-05-tools-as-dependencies/out/gen_out.cue
- guides/2020-11-08-retracting-module-versions/out/gen_out.cue
> deps: latest preguide to remove hardcoding of <b> emphasis in code

- .binaryfiles
- _posts/2020-11-08-retracting-module-versions_go116_en.markdown
- go.mod
- go.sum
- guides/2020-09-01-basic-go-modules-example/out/gen_out.cue
- guides/2020-10-07-intro-to-play-with-go-dev/out/gen_out.cue
- guides/2020-10-15-get-started-with-go/out/gen_out.cue
- guides/2020-10-19-go-fundamentals/out/gen_out.cue
- guides/2020-11-05-tools-as-dependencies/out/gen_out.cue
- guides/2020-11-08-retracting-module-versions/en.markdown
- guides/2020-11-08-retracting-module-versions/go116_en_log.txt
- guides/2020-11-08-retracting-module-versions/guide.cue
- guides/2020-11-08-retracting-module-versions/out/gen_out.cue
- guides/guide.cue
Also fix a small bug in the module retraction guide with 1 minute sleep,
per docs
> deps: latest preguide to pick up PREGUIDE_PROCESS support

- .github/workflows/test.yml
- .github/workflows/testmac.yml
- go.mod
- go.sum
- guides/2020-09-01-basic-go-modules-example/out/gen_out.cue
- guides/2020-10-07-intro-to-play-with-go-dev/out/gen_out.cue
- guides/2020-10-15-get-started-with-go/out/gen_out.cue
- guides/2020-10-19-go-fundamentals/out/gen_out.cue
- guides/2020-11-05-tools-as-dependencies/out/gen_out.cue
- guides/2020-11-08-retract-module-versions/out/gen_out.cue
- guides/2020-11-09-installing-programs-standalone/out/gen_out.cue
- guides/2020-11-09-using-staticcheck/out/gen_out.cue
- internal/ci/workflows.cue
Also upgrade to use Go 1.15.4 in CI
> deps: latest preguide and gitea

- cmd/controller/controller.go
We will be re-looking at deployment as part of #17. Until then, keep
things simple.
Fixes #153
> cmd/controller: load files from disk at startup, not each request

- go.mod
- go.sum
- guides/2018-10-19-go-fundamentals/out/gen_out.cue
- guides/2019-10-15-get-started-with-go/out/gen_out.cue
- guides/2020-08-13-installing-go/out/gen_out.cue
- guides/2020-09-01-basic-go-modules-example/out/gen_out.cue
- guides/2020-10-07-intro-to-play-with-go-dev/out/gen_out.cue
- guides/2020-11-05-tools-as-dependencies/out/gen_out.cue
- guides/2020-11-08-retract-module-versions/out/gen_out.cue
- guides/2020-11-09-installing-go-programs-directly/out/gen_out.cue
- guides/2020-11-09-using-staticcheck/out/gen_out.cue
- guides/2020-11-12-working-with-private-modules/out/gen_out.cue
We are now using a tip version of mvdan.cc/sh instead of a WIP branch
(that was just for launch)
> deps: latest preguide

- _posts/2019-10-15-get-started-with-go_go115_en.markdown
- guides/2019-10-15-get-started-with-go/en.markdown
Admittedly, "packackages" is a cute word, but one "ack" should be enough. :)
> Fixed a typo

- .github/workflows/test.yml
- .github/workflows/wip.yml
- internal/ci/workflows.cue
So that we can upgrade in our own good time
> ci: fix to ubuntu-18.04

- go.mod
- go.sum
- guides/2018-10-19-go-fundamentals/out/gen_out.cue
- guides/2019-10-15-get-started-with-go/out/gen_out.cue
- guides/2020-08-13-installing-go/out/gen_out.cue
- guides/2020-09-01-basic-go-modules-example/out/gen_out.cue
- guides/2020-10-07-intro-to-play-with-go-dev/out/gen_out.cue
- guides/2020-11-05-tools-as-dependencies/out/gen_out.cue
- guides/2020-11-08-retract-module-versions/out/gen_out.cue
- guides/2020-11-09-installing-go-programs-directly/out/gen_out.cue
- guides/2020-11-09-using-staticcheck/out/gen_out.cue
- guides/2020-11-12-working-with-private-modules/out/gen_out.cue
- guides/2020-11-19-major-version-repository-structure/out/gen_out.cue
Should now mean out packages are stable for the same input
> deps: latest preguide; for latest CUE and out pkg fixes

- _posts/2018-10-19-go-fundamentals_go115_en.markdown
- guides/2018-10-19-go-fundamentals/go115_en_log.txt
- guides/2018-10-19-go-fundamentals/out/gen_out.cue
- guides/2019-10-15-get-started-with-go/out/gen_out.cue
- guides/2020-08-13-installing-go/out/gen_out.cue
- guides/2020-09-01-basic-go-modules-example/out/gen_out.cue
- guides/2020-10-07-intro-to-play-with-go-dev/out/gen_out.cue
- guides/2020-11-05-tools-as-dependencies/out/gen_out.cue
- guides/2020-11-08-retract-module-versions/out/gen_out.cue
- guides/2020-11-09-installing-go-programs-directly/out/gen_out.cue
- guides/2020-11-09-using-staticcheck/out/gen_out.cue
- guides/2020-11-12-working-with-private-modules/out/gen_out.cue
- guides/2020-11-19-major-version-repository-structure/out/gen_out.cue
- guides/gen_guide_structures.cue
- guides/guide.cue
VSCode integration can follow later
> guides: use images that have vim and nano installed

- _scripts/generateGuides.sh
This makes it easier to re-run specific guides
> scripts: interpret args to generateGuides as patterns for PREGUIDE_RUN

- guides.html
Fixes #338
Signed-off-by: Marcos Lilljedahl <marcosnils@gmail.com>
> Make whole card link clickable

- _posts/2018-10-19-go-fundamentals_go115_en.markdown
- _posts/2019-10-15-get-started-with-go_go115_en.markdown
- _posts/2020-08-13-installing-go_go115_en.markdown
- guides/2018-10-19-go-fundamentals/en.markdown
- guides/2019-10-15-get-started-with-go/en.markdown
- guides/2020-08-13-installing-go/en.markdown
Checked locally with:
wget --execute robots=off --recursive --no-parent --continue \
http://localhost:4000
> guides: fix further broken links

- _posts/2020-11-12-working-with-private-modules_go115_en.markdown
- cue.mod/tests/eval.txt
- guides/2020-11-12-working-with-private-modules/go115_en_log.txt
- guides/2020-11-12-working-with-private-modules/out/gen_out.cue
> guides: update for new proxy.golang.org error messages

- cue.mod/tests/eval.txt
- go.mod
- go.sum
- guide.cue
- guides/2018-10-19-go-fundamentals/out/gen_out.cue
- guides/2019-10-15-get-started-with-go/out/gen_out.cue
- guides/2020-08-13-installing-go/out/gen_out.cue
- guides/2020-09-01-basic-go-modules-example/out/gen_out.cue
- guides/2020-10-07-intro-to-play-with-go-dev/out/gen_out.cue
- guides/2020-11-05-tools-as-dependencies/out/gen_out.cue
- guides/2020-11-08-retract-module-versions/out/gen_out.cue
- guides/2020-11-09-installing-go-programs-directly/out/gen_out.cue
- guides/2020-11-09-using-staticcheck/out/gen_out.cue
- guides/2020-11-12-working-with-private-modules/out/gen_out.cue
- guides/2020-11-19-major-version-repository-structure/out/gen_out.cue
- guides/2021-05-06-gosheffield-demo/out/gen_out.cue
- guides/gen_guide_structures.cue
> guides: latest preguide and docker images

- _posts/2022-09-23-london-gophers-cue_go119_en.markdown
- cue.mod/tests/eval.txt
- guides/2022-09-23-london-gophers-cue/en.markdown
- guides/2022-09-23-london-gophers-cue/go119_en_log.txt
- guides/2022-09-23-london-gophers-cue/guide.cue
- guides/2022-09-23-london-gophers-cue/out/gen_out.cue
- guides/gen_guide_structures.cue
> guides: initial cut of London Gophers CUE talk from 2022

- _posts/2018-10-19-go-fundamentals_go119_en.markdown
- _posts/2020-11-12-working-with-private-modules_go119_en.markdown
- _posts/2022-09-23-london-gophers-cue_go119_en.markdown
- cue.mod/tests/eval.txt
- guide.cue
- guides/2018-10-19-go-fundamentals/go119_en_log.txt
- guides/2018-10-19-go-fundamentals/out/gen_out.cue
- guides/2019-10-15-get-started-with-go/out/gen_out.cue
- guides/2020-08-13-installing-go/out/gen_out.cue
- guides/2020-11-05-tools-as-dependencies/out/gen_out.cue
- guides/2020-11-08-retract-module-versions/out/gen_out.cue
- guides/2020-11-09-installing-go-programs-directly/out/gen_out.cue
- guides/2020-11-09-using-staticcheck/out/gen_out.cue
- guides/2020-11-12-working-with-private-modules/go119_en_log.txt
- guides/2020-11-12-working-with-private-modules/out/gen_out.cue
- guides/2020-11-19-major-version-repository-structure/out/gen_out.cue
- guides/2022-09-23-london-gophers-cue/go119_en_log.txt
- guides/2022-09-23-london-gophers-cue/out/gen_out.cue
> guides: fix 'go version' linebreak bug

- _posts/2022-09-23-london-gophers-cue_go119_en.markdown
- cue.mod/tests/eval.txt
- guides/2022-09-23-london-gophers-cue/en.markdown
- guides/2022-09-23-london-gophers-cue/go119_en_log.txt
- guides/2022-09-23-london-gophers-cue/guide.cue
- guides/2022-09-23-london-gophers-cue/out/gen_out.cue
> guides: tidy up London Gophers CUE talk
