play-with-go/play-with-go

- _posts/2020-09-01-basic-go-modules-example.markdown
- guides/2020-09-01-basic-go-modules-example/en_log.txt
- guides/2020-09-01-basic-go-modules-example/guide.cue
- guides/2020-09-01-basic-go-modules-example/out/gen_out.cue
- guides/gen_guide_structures.cue
- guides/guide.cue
In order that we don't have to special case guides that use go list with
{{  }}
> guides: use {{{ }}} delims by default

- _scripts/dc.sh
This allows us to musl libc docker images when running on Linux
> Explicitly set CGO_ENABLED=0

- cmd/controller/controller.go
The browser doesn't send cookies on CORS requests, so
don't validate the cookie in this case
> Don't authenticate CORS auth

- docs/js/post-layout.js
- js/post-layout.js
Only applies to non-compat mode, but making this change now so we don't
forget to later.
> js: decode data-upload-path when "fixing" attributes of code blocks

- docker/site/Dockerfile
- docker/site/entrypoint
- docker/site/jekyll
The default jekyll image does some werid things when passed a JEKYLL_UID
and JEKYLL_GID value. It tries to modify the existing, build-created,
jekyll user in the container. However, this will not work if the passed
values happen to conflict with an existing user/group.
Instead, the entrypoint should define that JEKYLL_UID and JEKYLL_GID
represent the UID and GID as which the caller wants to run everything.
The jekyll user is really irrelevant in all of this.
Hence, we now provide a custom entrypoint and jekyll wrapper that
drives everything off JEKYLL_UID and JEKYLL_GID
> docker: fix site generate

- _scripts/generateEverythingElse.sh
This must only be a temporary container
> _scripts: remove the container we use when generating the site

- _posts/2020-10-07-intro-to-play-with-go-dev.markdown
- guides/2020-10-07-intro-to-play-with-go-dev/en.markdown
- guides/2020-10-07-intro-to-play-with-go-dev/en_log.txt
- guides/2020-10-07-intro-to-play-with-go-dev/guide.cue
- guides/2020-10-07-intro-to-play-with-go-dev/out/gen_out.cue
- guides/gen_guide_structures.cue
Gives details on how guides are auto-initialised with a module path,
that also doubles as the remote VCS
> guides: improve intro to PWG with details of gitea repos

- cmd/controller/controller.go
- docker/controller/Dockerfile
This allows this image to be used in production. While used locally, the
files can/will be override by any possible volume mounts.
@myitcv I had to do this to deploy the controller image in prod since it was missing this files. Not sure If this is the proper way of doing it, but it works until we find a better way to deploy this.
> Add cue files to controller image

- _posts/2020-11-12-working-with-private-modules_go115_en.markdown
- go.mod
- go.sum
- guides/2020-09-01-basic-go-modules-example/out/gen_out.cue
- guides/2020-10-07-intro-to-play-with-go-dev/out/gen_out.cue
- guides/2020-10-15-get-started-with-go/out/gen_out.cue
- guides/2020-10-19-go-fundamentals/out/gen_out.cue
- guides/2020-11-05-tools-as-dependencies/out/gen_out.cue
- guides/2020-11-08-retract-module-versions/out/gen_out.cue
- guides/2020-11-09-installing-programs-standalone/out/gen_out.cue
- guides/2020-11-09-using-staticcheck/out/gen_out.cue
- guides/2020-11-12-working-with-private-modules/go115_en_log.txt
- guides/2020-11-12-working-with-private-modules/guide.cue
- guides/2020-11-12-working-with-private-modules/out/gen_out.cue
Otherwise it will always result in changes after a
PREGUIDE_SKIP_CACHE=true run.
Also upgrade to the latest preguide which includes a fix for sanitising
the output of go get when it includes a module VCS cache path
> guides: add InformationOnly steps for private modules guide

- _posts/2020-11-12-working-with-private-modules_go115_en.markdown
- guides/2020-11-12-working-with-private-modules/en.markdown
> guides: fix misspelling

- _posts/2020-11-12-working-with-private-modules_go115_en.markdown
- guides/2020-11-12-working-with-private-modules/go115_en_log.txt
- guides/2020-11-12-working-with-private-modules/guide.cue
- guides/2020-11-12-working-with-private-modules/out/gen_out.cue
go.mod files were not git add-ed, hence were never published. This hid
the fact that both modules in fact had the wrong path, i.e. they were
not fully qualified.
Thanks to @ardan-bkennedy for spotting this.
The automated fix that catches these sorts of issues is covered by
play-with-go/preguide#153.
> guides: fix a bug in the private modules guide

- _posts/2018-10-19-go-fundamentals_go115_en.markdown
- _posts/2020-09-01-basic-go-modules-example_go115_en.markdown
- guides/2018-10-19-go-fundamentals/go115_en_log.txt
- guides/2018-10-19-go-fundamentals/guide.cue
- guides/2018-10-19-go-fundamentals/out/gen_out.cue
- guides/2020-09-01-basic-go-modules-example/go115_en_log.txt
- guides/2020-09-01-basic-go-modules-example/guide.cue
- guides/2020-09-01-basic-go-modules-example/out/gen_out.cue
- guides/2020-11-08-retract-module-versions/go116_en_log.txt
- guides/2020-11-08-retract-module-versions/guide.cue
- guides/2020-11-08-retract-module-versions/out/gen_out.cue
- guides/2020-11-12-working-with-private-modules/go115_en_log.txt
- guides/2020-11-12-working-with-private-modules/guide.cue
- guides/2020-11-12-working-with-private-modules/out/gen_out.cue
- guides/2020-11-19-major-version-repository-structure/go115_en_log.txt
- guides/2020-11-19-major-version-repository-structure/guide.cue
- guides/2020-11-19-major-version-repository-structure/out/gen_out.cue
This will automated at a later stage by play-with-go/preguide#153 (or
indeed by guides which are more verbose in their explanation to use,
e.g. running a git status after a git commit to show the state is
"clean") but for now add InformationOnly steps that verify we have a
clean working tree after creating a commit.
Fix a couple of instances where that was not the case.
> guides: fix bad git add commands

- _posts/2018-10-19-go-fundamentals_go115_en.markdown
- guides/2018-10-19-go-fundamentals/en.markdown
Hello🙂 Thank you for creating a great learning environment! It's very helpful to learn Golang.
I found markdown errors in guides/2018-10-19-go-fundamentals. The closing parenthesis should be inside the quotation.
> Fix the markup of commands

- index.html
Hello, this is just a small fix. This fixes the case of "Github" to "GitHub" on the landing page.
I searched all the files and there is no other "Github".
**Screenshot after the change**
> Replate "Github" with "GitHub" on the top page

- _posts/2020-11-09-installing-go-programs-directly_go116_en.markdown
- _scripts/generateGuides.sh
- guides/2020-11-09-installing-go-programs-directly/en.markdown
- guides/2020-11-09-installing-go-programs-directly/go116_en_log.txt
- guides/2020-11-09-installing-go-programs-directly/guide.cue
- guides/2020-11-09-installing-go-programs-directly/out/gen_out.cue
Specify the version of mkcert we want to go get; add a comment
explaining why we need to do that.
> guides: make installing-go-programs-directly reproducible

- _posts/2018-10-19-go-fundamentals_go115_en.markdown
- cue.mod/pkg/github.com/play-with-go/preguide/out/out.cue
- cue.mod/pkg/github.com/play-with-go/preguide/preguide.cue
- go.mod
- go.sum
- guides/2018-10-19-go-fundamentals/go115_en_log.txt
- guides/2018-10-19-go-fundamentals/out/gen_out.cue
- guides/2019-10-15-get-started-with-go/out/gen_out.cue
- guides/2020-08-13-installing-go/out/gen_out.cue
- guides/2020-09-01-basic-go-modules-example/out/gen_out.cue
- guides/2020-10-07-intro-to-play-with-go-dev/out/gen_out.cue
- guides/2020-11-05-tools-as-dependencies/out/gen_out.cue
- guides/2020-11-08-retract-module-versions/out/gen_out.cue
- guides/2020-11-09-installing-go-programs-directly/out/gen_out.cue
- guides/2020-11-09-using-staticcheck/out/gen_out.cue
- guides/2020-11-12-working-with-private-modules/out/gen_out.cue
- guides/2020-11-19-major-version-repository-structure/out/gen_out.cue
This is not on for now, but can be turned on for individual guides or
all of them.
> deps: latest preguide; can comment file blocks with target location

- docker/cmd_gitea/Dockerfile
- docker/controller/Dockerfile
- docker/l2/Dockerfile
- docker/pwd/Dockerfile
We don't need to copy the entire of the PWG directory in most cases.
Doing so also invalidates the build unnecessarily, because buildkit
can't know/work out that a build is not required
> ci: optimise Dockerfile's used as part of compose setup

- _posts/2018-10-19-go-fundamentals_go115_en.markdown
- guides/2018-10-19-go-fundamentals/go115_en_log.txt
- guides/2018-10-19-go-fundamentals/out/gen_out.cue
- guides/2019-10-15-get-started-with-go/out/gen_out.cue
- guides/2020-08-13-installing-go/out/gen_out.cue
- guides/2020-09-01-basic-go-modules-example/out/gen_out.cue
- guides/2020-10-07-intro-to-play-with-go-dev/out/gen_out.cue
- guides/2020-11-05-tools-as-dependencies/out/gen_out.cue
- guides/2020-11-08-retract-module-versions/out/gen_out.cue
- guides/2020-11-09-installing-go-programs-directly/out/gen_out.cue
- guides/2020-11-09-using-staticcheck/out/gen_out.cue
- guides/2020-11-12-working-with-private-modules/out/gen_out.cue
- guides/2020-11-19-major-version-repository-structure/out/gen_out.cue
- guides/gen_guide_structures.cue
- guides/guide.cue
This isn't perfect because we still have a hack whereby the upload of a
file is faked as a command. We should make this a proper command (as a
comment) in any case.
> guides: use latest docker images for improved prompt

- _scripts/generateEverythingElse.sh
- docker/site/Dockerfile
In our base image for the site part of Docker compose, we were running:
RUN gem install jekyll-toc
This installed the latest versio of jekyll-toc at that point in time.
Which is a) clearly not reproducible, and b) liable to be brittle in the
presence of bad new versions.
Exactly that happened this morning with the release of v0.17.0, which
started to give rise to errors reported in:
https://github.com/toshimaru/jekyll-toc/issues/141
This change installs a specific version of that dependency to make this
more resilient.
> docker: install a specific version of jekyll-toc

- .github/workflows/test.yml
- .github/workflows/testmac.yml
- docker/cmd_gitea/Dockerfile
- docker/controller/Dockerfile
- docker/l2/Dockerfile
- docker/pwd/Dockerfile
- internal/ci/workflows.cue
We currently use an experimental version of dockerfile. Use an official
version of the buildkit frontend.
Also make a minor tweak to CI to use an explicit version of Ubuntu
rather than the moving feast that is "latest".
Also use the latest Go in CI.
> docker: use official docker/dockerfile image

- _posts/2018-10-19-go-fundamentals_go115_en.markdown
- guide.cue
- guides/2018-10-19-go-fundamentals/go115_en_log.txt
- guides/2018-10-19-go-fundamentals/out/gen_out.cue
- guides/2019-10-15-get-started-with-go/out/gen_out.cue
- guides/2020-08-13-installing-go/out/gen_out.cue
- guides/2020-09-01-basic-go-modules-example/out/gen_out.cue
- guides/2020-10-07-intro-to-play-with-go-dev/out/gen_out.cue
- guides/2020-11-05-tools-as-dependencies/out/gen_out.cue
- guides/2020-11-08-retract-module-versions/out/gen_out.cue
- guides/2020-11-09-installing-go-programs-directly/out/gen_out.cue
- guides/2020-11-09-using-staticcheck/out/gen_out.cue
- guides/2020-11-12-working-with-private-modules/out/gen_out.cue
- guides/2020-11-19-major-version-repository-structure/out/gen_out.cue
- guides/gen_guide_structures.cue
Use the latest Docker images based on commit:
323f3c41f7777318a1c4228fe2c0ec492054fd87
from the https://github.com/play-with-go/docker repo.
> guides: use latest Docker images

- _posts/2020-11-05-tools-as-dependencies_go115_en.markdown
- go.mod
- go.sum
- guides/2018-10-19-go-fundamentals/out/gen_out.cue
- guides/2019-10-15-get-started-with-go/out/gen_out.cue
- guides/2020-08-13-installing-go/out/gen_out.cue
- guides/2020-09-01-basic-go-modules-example/out/gen_out.cue
- guides/2020-10-07-intro-to-play-with-go-dev/out/gen_out.cue
- guides/2020-11-05-tools-as-dependencies/go115_en_log.txt
- guides/2020-11-05-tools-as-dependencies/out/gen_out.cue
- guides/2020-11-08-retract-module-versions/out/gen_out.cue
- guides/2020-11-09-installing-go-programs-directly/out/gen_out.cue
- guides/2020-11-09-using-staticcheck/out/gen_out.cue
- guides/2020-11-12-working-with-private-modules/out/gen_out.cue
- guides/2020-11-19-major-version-repository-structure/out/gen_out.cue
Allows us to load preguide config irrespective of build constraints.
This is a hack for now until we have a better solution from preguide.
> deps: use latest preguide with fix for config loading

- _config.yml
- _posts/2020-11-08-retract-module-versions_go116_en.markdown
- _posts/2020-11-09-installing-go-programs-directly_go116_en.markdown
- guides/2020-11-08-retract-module-versions/en.markdown
- guides/2020-11-09-installing-go-programs-directly/en.markdown
Go 1.16 released and these features are officially now. So I think "preview" is no need.
> guides: remove mention about a preview

- _scripts/macCISetup.sh
- cue.mod/tests/eval.txt
Docker v3.2.0 was broken for mac. Explicitly use v3.2.1. Per:
https://github.com/docker/for-mac/issues/5406
> ci: fix mac CI run

- _posts/2018-10-19-go-fundamentals_go115_en.markdown
- guides/2018-10-19-go-fundamentals/en.markdown
With thanks to @andersarpi and @peterhellberg for reporting this.
> guides: fix link to prerequisites for fundamentals guides

- _posts/2021-05-02-build-flags-backwards-compatibility_go115_en.markdown
- cue.mod/tests/eval.txt
- guide.cue
- guides/2021-05-02-build-flags-backwards-compatibility/en.markdown
- guides/2021-05-02-build-flags-backwards-compatibility/go115_en_log.txt
- guides/2021-05-02-build-flags-backwards-compatibility/guide.cue
- guides/2021-05-02-build-flags-backwards-compatibility/out/gen_out.cue
- guides/gen_guide_structures.cue
- guides/guides.go
This guide also depend on https://github.com/play-with-go/preguide/issues/194 and https://github.com/play-with-go/preguide/issues/193 outcomes. 
Pretty much all the guide is there, what's missing is just the conclusion and of course some good semantic and orthographic review. cc @myitcv  :)
> New guide to show case how to handle go version backwards compatibility

- .github/workflows/test.yml
- .github/workflows/testmac.yml
- _posts/2021-05-02-build-flags-backwards-compatibility_go115_en.markdown
- cue.mod/tests/eval.txt
- guides/2021-05-02-build-flags-backwards-compatibility/go115_en_log.txt
- guides/2021-05-02-build-flags-backwards-compatibility/guide.cue
- guides/2021-05-02-build-flags-backwards-compatibility/out/gen_out.cue
- internal/ci/workflows.cue
Also, move the check for clean commit before the unity check. Otherwise,
any actual diff pre unity is lost with a simple "there were unstaged
changes"
> guides: fix build flags unstable output

- _posts/2020-11-09-installing-go-programs-directly_go116_en.markdown
- guides/2020-11-09-installing-go-programs-directly/en.markdown
This change replaces the broken link `https://mkcert.io` with a direct
link to the project repository `https://github.com/FiloSottile/mkcert`.
```
~>  curl -I https://mkcert.io
curl: (6) Could not resolve host: mkcert.io
```
> install-go-programs/en.markdown: Update link to mkcert source code
